sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm install
  - npm run build
  
jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Build
      script: npm run build
    - stage: Test
      script: npm run unit
